// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7iwGarFK4TIDNvaRhIZQqs4BAKw8aX_M',
    appId: '1:932597913265:web:c0426826c2d1123dd17490',
    messagingSenderId: '932597913265',
    projectId: 'taskmanagement-2170d',
    authDomain: 'taskmanagement-2170d.firebaseapp.com',
    databaseURL: 'https://taskmanagement-2170d-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanagement-2170d.firebasestorage.app',
    measurementId: 'G-E44TZCBRVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8587HuXG9tUwm3fn8CptPRyu11XnaVs',
    appId: '1:932597913265:android:c31e15ab2761c387d17490',
    messagingSenderId: '932597913265',
    projectId: 'taskmanagement-2170d',
    databaseURL: 'https://taskmanagement-2170d-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanagement-2170d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Np-ot0RSJo7vXB2mwHyQ8O8EkPmZSQI',
    appId: '1:932597913265:ios:c293762a42dab4a8d17490',
    messagingSenderId: '932597913265',
    projectId: 'taskmanagement-2170d',
    databaseURL: 'https://taskmanagement-2170d-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanagement-2170d.firebasestorage.app',
    iosClientId: '932597913265-n7i6nvju0tbhovoeo6komfnrvule3lp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Np-ot0RSJo7vXB2mwHyQ8O8EkPmZSQI',
    appId: '1:932597913265:ios:c293762a42dab4a8d17490',
    messagingSenderId: '932597913265',
    projectId: 'taskmanagement-2170d',
    databaseURL: 'https://taskmanagement-2170d-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanagement-2170d.firebasestorage.app',
    iosClientId: '932597913265-n7i6nvju0tbhovoeo6komfnrvule3lp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7iwGarFK4TIDNvaRhIZQqs4BAKw8aX_M',
    appId: '1:932597913265:web:653cea5bb327b8bcd17490',
    messagingSenderId: '932597913265',
    projectId: 'taskmanagement-2170d',
    authDomain: 'taskmanagement-2170d.firebaseapp.com',
    databaseURL: 'https://taskmanagement-2170d-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanagement-2170d.firebasestorage.app',
    measurementId: 'G-Q4ZVXM2FSE',
  );
}
